# Generated by Django 4.2.30 on 2026-06-17 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('stock_price_local', models.DecimalField(decimal_places=4, max_digits=15)),
                ('stock_price_usd', models.DecimalField(decimal_places=4, max_digits=15)),
                ('purchased_at', models.DateTimeField()),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='core.broker')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='core.stock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'posición',
                'verbose_name_plural': 'posiciones',
                'db_table': 'position',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('fulfill_datetime', models.DateTimeField()),
                ('total_fees', models.DecimalField(decimal_places=4, max_digits=15)),
                ('price_local', models.DecimalField(decimal_places=4, max_digits=15)),
                ('price_usd', models.DecimalField(decimal_places=4, max_digits=15)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='portfolio.position')),
            ],
            options={
                'verbose_name': 'orden',
                'verbose_name_plural': 'órdenes',
                'db_table': 'order',
            },
        ),
    ]
