# Generated by Django 6.1 on 2026-08-28 01:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('ARS', 'Pesos (ARS)'), ('USD', 'Dólares (USD)')], max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_positions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'liquidez',
                'verbose_name_plural': 'liquidez',
                'db_table': 'cash_position',
                'ordering': ['currency', '-created_at'],
            },
        ),
    ]
