# Generated by Django 6.1 on 2026-09-23 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_remove_order_and_position_fields'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='lot',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='lot_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='lot',
            constraint=models.CheckConstraint(condition=models.Q(('price_local__gt', 0)), name='lot_price_local_positive'),
        ),
        migrations.AddConstraint(
            model_name='lot',
            constraint=models.CheckConstraint(condition=models.Q(('price_usd__gt', 0)), name='lot_price_usd_positive'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='sale_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(('price_local__gt', 0)), name='sale_price_local_positive'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(('price_usd__gt', 0)), name='sale_price_usd_positive'),
        ),
    ]
