# Generated by Django 6.1 on 2026-09-23 02:06

from django.conf import settings
from django.db import migrations, models


def separate_existing_recoveries(apps, schema_editor):
    CashTransaction = apps.get_model('portfolio', 'CashTransaction')
    CashTransaction.objects.filter(tipo='recupero', sale__isnull=False).update(tipo='venta')
    CashTransaction.objects.filter(tipo='recupero').update(tipo='reembolso')


def merge_transaction_types(apps, schema_editor):
    CashTransaction = apps.get_model('portfolio', 'CashTransaction')
    CashTransaction.objects.filter(tipo__in=['venta', 'reembolso']).update(tipo='recupero')


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_enforce_positive_trade_values'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashtransaction',
            name='tipo',
            field=models.CharField(choices=[('compra', 'Compra'), ('venta', 'Venta'), ('reembolso', 'Reembolso por eliminación')], max_length=10),
        ),
        migrations.RunPython(separate_existing_recoveries, merge_transaction_types),
        migrations.AddConstraint(
            model_name='cashtransaction',
            constraint=models.CheckConstraint(condition=models.Q(('tipo__in', ['compra', 'venta', 'reembolso'])), name='cash_transaction_tipo_valid'),
        ),
    ]
