# Generated by Django 4.2.30 on 2026-06-17 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'alerta',
                'verbose_name_plural': 'alertas',
                'db_table': 'alert',
            },
        ),
        migrations.CreateModel(
            name='TechnicalIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('period', models.IntegerField(default=14)),
            ],
            options={
                'verbose_name': 'indicador técnico',
                'verbose_name_plural': 'indicadores técnicos',
                'db_table': 'technical_indicator',
            },
        ),
        migrations.CreateModel(
            name='AlertTrigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_datetime', models.DateTimeField(auto_now_add=True)),
                ('ai_recommendation', models.TextField(blank=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to='alerts.alert')),
            ],
            options={
                'verbose_name': 'disparo de alerta',
                'verbose_name_plural': 'disparos de alerta',
                'db_table': 'alert_trigger',
            },
        ),
        migrations.CreateModel(
            name='AlertCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(max_length=10)),
                ('threshold_value', models.DecimalField(decimal_places=4, max_digits=15)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='alerts.technicalindicator')),
            ],
            options={
                'verbose_name': 'condición de alerta',
                'verbose_name_plural': 'condiciones de alerta',
                'db_table': 'alert_condition',
            },
        ),
        migrations.AddField(
            model_name='alert',
            name='conditions',
            field=models.ManyToManyField(related_name='alerts', to='alerts.alertcondition'),
        ),
    ]
