# Generated by Django 6.1 on 2026-09-23 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertcondition',
            name='operator',
            field=models.CharField(choices=[('>', '>'), ('<', '<'), ('>=', '>='), ('<=', '<='), ('==', '=='), ('!=', '!=')], max_length=10),
        ),
        migrations.AddConstraint(
            model_name='alertcondition',
            constraint=models.CheckConstraint(condition=models.Q(('operator__in', ['>', '<', '>=', '<=', '==', '!='])), name='alert_condition_operator_valid'),
        ),
    ]
