# Generated by Django 6.1 on 2026-08-28 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['tipo', 'ticker'], 'verbose_name': 'instrumento', 'verbose_name_plural': 'instrumentos'},
        ),
        migrations.AddField(
            model_name='stock',
            name='tipo',
            field=models.CharField(choices=[('accion', 'Acción'), ('cedear', 'CEDEAR'), ('bono', 'Bono'), ('letra', 'Letra')], default='accion', max_length=10),
        ),
    ]
