# Generated by Django 6.1 on 2026-09-25 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_stock_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='cedear_kind',
            field=models.CharField(blank=True, choices=[('company', 'Empresa'), ('etf', 'ETF')], max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='classification_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='classification_manual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stock',
            name='classification_source',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='stock',
            name='instrument_family',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='stock',
            name='issuer_type',
            field=models.CharField(blank=True, choices=[('national', 'Nacional / soberano'), ('provincial', 'Provincial'), ('municipal', 'Municipal'), ('bcra', 'BCRA'), ('corporate', 'Corporativo'), ('trust', 'Fideicomiso'), ('other', 'Otro')], max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='payment_style',
            field=models.CharField(blank=True, choices=[('capitalizable', 'Capitalizable'), ('periodic_coupon', 'Cupón periódico'), ('step_up', 'Step-up'), ('discount', 'A descuento'), ('zero_coupon', 'Cero cupón'), ('other', 'Otra')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='rate_reference',
            field=models.CharField(blank=True, choices=[('fixed', 'Tasa fija'), ('cer', 'CER'), ('tamar', 'TAMAR'), ('dollar_linked', 'Dólar linked'), ('dual', 'Dual'), ('other', 'Otra')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='underlying_ticker',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
